### ISSUE TITLE
2.1.0 Issues & PRs to be merged

### ISSUE THREAD

**Issue by MurdoMaclachlan** [MurdoMaclachlan/oscr#124]
## Functionality

- [x] Add refresh token support (#33, #139)
- [x] Add "dibs" to default blacklist and regexBlacklist (#140, #141)
- [x] Remove `--format-old` (#105, #131)

## Cleanup/Optmisation

- [x] Split `main.py` code into smaller functions for readability (#128, #145)
- [x] Optimise the settings menu to allow for easier addition of new config and ini options (#127, #139, #142)
- [x] Combine `Log.clear()` and `Log.get()` into one `Log.request()` (#125, #130)
- [x] General cleanup, readability and optimisation improvements (#136, #137, #139, #142, #145)

## Dependencies

- None planned

## Documentation

- [x] Change "core" folder to "oscrcore" (#138, #139)

## Bug Fixes

- [x] #132: Crash on calling `resetConfig()` (fixed in #134)
- [x] #133: Crash on passing unknown run-time argument (fixed in #135)
