### ISSUE TITLE
2.2.0 Issues and PRs to be merged

### ISSUE THREAD

**Issue by MurdoMaclachlan** [MurdoMaclachlan/oscr#150]
## Functionality

- [x] Change to default regex to allow saving of a claim/done comment. (#161, #162)
- [x] Make `Globals.config` use proper encapsulation. (#151, #175)

## Cleanup/Optimisation

- [ ] Blacken all modules. (#152)
- [x] Divide `globals.py` into two modules; `classes.py`, containing all classes, and `globals.py`, containing all global variables. (#153, #168)

## Dependencies

No changes planned yet.

## Documentation

- [x] Change function/variable naming from camelCase to snake_case. (#154, #160)
- [x] Change config keys from camelCase to snake_case. (#169, #168, #176)
- [x] Add docstrings to all modules. (#155, #158)
- [x] Rename `ini.py` to `creds.py`. (#156, #168)

## Bug Fixes

- [x] Fix crash due to misnamed attribute on `fetch_stats()` failing to find `stats.json`. (#157, #160)
- [x] Fix refresh token not being properly saved to praw.ini. (#163, #170)
- [x] Fix possible reference before assignment if `praw.ini` is not found in `edit_credentials()`. (#164, #171)
- [x] Fix crash when editing arrays in `edit_config()` due to old variable name references. (#165, #172)
- [x] Change default argument for `update_log()` to `None`. (#166, #173)
- [x] Fix unfilled argument when calling `dump_credentials()` in `edit_credentials()` (#167, #174)
