### ISSUE TITLE
2.0.0 Issues & PRs to be merged

### ISSUE THREAD

**Issue by MurdoMaclachlan** [MurdoMaclachlan/oscr#42]
Now, don't get excited. This will probably take a while (when I say a while, university means a while), especially since these planned changes will no doubt build up.

## Functionality

- [x] #57, #69: Add caseSensitive config key (False by default).
- [x] #48, #87, #115: Add --clean-hunt option to remove comments containing "treasure hunt". (requires #85)
- [x] #69: Add "unclaiming" to default blacklist.
- [x] #70, #71: Add printLogs options (config key and argument).
- [x] #65, #72: Add reportTotals options (config key and argument).
- [x] #49, #75: Collect gvars at program initialisation (oscr) and not main.py.
- [x] #50, #75: Contain all main.py code in oscr() function for this purpose.
- [x] #80, #82: Ignore punctuation when removing comments via blacklist.
- [x] #85, #87: Add userList option and only check comments that are replies to these users. (necessary for #48)
- [x] Allow subredditList and userList to be disabled by leaving them empty.

## Cleanup/Optimisation

- [x] #106, #109: Re-write stats handling using JSON and classes.
- [x] #108, #109, #112: Refactor with much stronger object-oriented focus.
- [x] #52, #75: Move arguments checking to a specific module; arguments.py.
- [x] #53, #59: Don't call calculateEssentials() unless actually essential.
- [x] #51, #66, #67: Optimise generation of config.json and praw.ini.
- [x] #77, #78, #79, #84, #96, #104, #109, #112, #114, #118, #120, #121: General readability/optimisation improvements.
- [x] #76, #84: Optimise handling of praw.ini, including updating & formatting from CDRemover to OSCR. (requires #55)
- [x] #81, #82: Move comment handling to comment.py module.
- [x] #97, #96, #98: Staticise constant variables.
- [x] #101, #103: Add type hinting.
- [x] #117, #118: Combine default regexBlacklist items into one regex.

## Dependencies

- [x] #94: Require colored (necessary for #91)
- [x] #107: Require Python >= 3.5 (necessary for #103)

## Documentation

- [x] #110, #111: Rename oscrmodules to core.
- [x] #54, #64: Move config.json to a .config/oscr folder.
- [x] #55, #84: Change the way praw.ini is read so the file can be in ~/.config/oscr (Linux and Mac) or whatever the path to AppData is on Windows.
- [x] #56, #66: Move defaultConfig to gvars.py; its presence in misc.py is not good for readability.
- [x] #60, #68: Improve log output surrounding comment retrieval & checking.
- [x] #73, #74: Add license specification to setup.py.
- [x] #83: Change config guide from bullet point list to table.
- [x] #91, #94: Add colouring to logs.
- [x] #93, #99: Move documentation to readthedocs.
- [x] #95, #96: General improvements to log handling.
- [x] #100, #102: Rename gvars to Globals.
- [x] #116, #119: Update documentation with new runtime and config options.

## Bug Fixes

- [x] #58, fix #45: Crash on attempting to use --show-config due to accidentally assigning Globals() instance to gvars.config.
- [x] #63, fix #61: Attempting to update integer or boolean keys in the settings menu causes an infinite loop.
- [x] #87, fix #86: Regexes may delete comments that are not bot interactions.
- [x] #90, fix #88: Arguments are not processed in correct priority order.
- [x] #90, fix #89: Crash on passing conflicting arguments.
- [x] #94, fix #92: Potential crash on failing to update statistic.

**Comment by MurdoMaclachlan** [comment]
I want to die. Fuck you, GitHub.
![image](https://user-images.githubusercontent.com/47920497/120943195-462cf180-c725-11eb-8695-a8a151b899d1.png)

**Comment by MurdoMaclachlan** [comment]
Totally fucking unreadable
![image](https://user-images.githubusercontent.com/47920497/125613854-07ce4efc-c109-463a-8e22-5291c5fa61f6.png)
Github why the fuck are you shit
